- python
    - python is a programming paradism means it supports functional programming and objected oriented programming and also work with procedure orientd language 
- procedure oriented language
    - procedure oriented language means write  our programming language using  functions objects and classes
- object oriented lanuage
    - object:real world entity or it is a physicl entity repesented memory
    - class:logical entity contained

In [ ]:
# Syntax for class
class class_name:
    variables
    methods or function

In [1]:
print("hello world")

hello world


In [2]:
8+9

17

In [3]:
class Hi:
    a=10
    b=20
    name="apssdc"
    def show():
        print(" i am from show() function")


In [4]:
Hi.name

'apssdc'

In [5]:
Hi.show()

 i am from show() function


In [6]:
Hi.a

10

In [7]:
Hi.b

20

In [8]:
print(Hi.a,Hi.b)

10 20


In [9]:
class Hi:
    name="apssdc"
    program_name="python"
    def display():
        print("i am from display function()")
    def show():
        print("i am from show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())

apssdc python
i am from display function()
None


In [10]:
print(Hi.display())

i am from display function()
None


In [3]:
class Hello():
    def display():
        print("i am from display function()")
        return("i am from return statment")
    def show():
        print("i am from show function()")
    
print(Hello.display())
print(Hello.show())

i am from display function()
i am from return statment
i am from show function()
None


In [ ]:
# java

In [7]:
class Hi:
    name="apssdc"
    program_name="python"
    def display(self):
        print("i am from display function()")
        return("i am from retuen statement")
    def show(hii):
        print("i am from show function()")
        return(" i am from return statment")
obj=Hi()

print(obj.name,Hi.program_name)
print(obj.display())
print(obj.show())

apssdc python
i am from display function()
i am from retuen statement
i am from show function()
 i am from return statment


### constructor
- constructor:without using object we will call method
    - in java:: class name should  be same as method name
    - in python:: we will use one special method to define constructor
    - __init(self)__

In [8]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('mahesh','21a85a0505')
obj.display()

hi mahesh
your roll_no 21a85a0505


### inheritance
- inherits something parient class to  child class

In [ ]:
class A:
    # a,b=10,20
class B(A):
    # c,d=40,50
    

In [11]:
class A:
    a,b=10,30
    def msg():
        print(" i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from child class B")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()

40 10
i am from child class B
 i am from class A


### Python libraries for data science 
- orginizing,processing,analyzing the huge amoung data
- apply data visulization
- extraction the data from the source
- nearly 20 pyhton libraries are there
# Top
- Numpy
- Pandas
- matplotlib
#### Numpy
- numpy::(num+py)means numerical data+python
- it is fundamental package for scientific computing in python
- numpy is the pyhton library
- it is used to create multidimensional array for fast operation
    - its dealing with mathemitcal,scientific,statical data
- numpy contains a power full n_dinemsional array pbject.which in the form rows and columns
- we can initilize numpy arrays from nested python list


In [ ]:
# how to install numpy
- pip install numpy

In [12]:
# how to import and use numpy package
import numpy as np

In [13]:
# how to find the numpy version
np.__version__

'1.20.3'

In [15]:
# how to create numpy array
import numpy as np
a=np.array([1,2,3,4]) # single dimensional number
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [18]:
a2=np.array([[2,3,4],[5,6,4]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 6 4]]
<class 'numpy.ndarray'>


In [19]:
# to know about the shape of the array
a2.shape

(2, 3)

In [21]:
li=[2,3,4,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [22]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
print(ar.dtype)

int32


In [24]:
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [25]:
b.itemsize

4

In [26]:
b.ndim

2

In [31]:
# range 
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [34]:
a=np.array(range(1,10,2))
a

array([1, 3, 5, 7, 9])

In [35]:
# arrange() -third party of numpy library
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [36]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
# reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("bedore reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
bedore reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [39]:
# resize of array(its modifies shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3) # resize the no of elements from originl array
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [51]:
# zero array 
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4))
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
float64
[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
# one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [44]:
# full array- full (dimentions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [45]:
np.diag(a)

array([7, 7, 7])

In [53]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [59]:
# eye array 
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [60]:
n=np.eye(5)

In [61]:
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [65]:
r=np.random.randint(1,10)

In [66]:
r

2

In [70]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[ 9,  9, 12,  9],
       [ 7,  4,  4,  4],
       [14,  7, 14, 12]])

In [71]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.6264008 , 0.9717027 , 0.12028593],
       [0.43304307, 0.18181975, 0.96545471]])

In [72]:
f=np.random.randn(2,3)

In [73]:
f

array([[-0.6776882 ,  1.22146583, -0.82675344],
       [ 0.37218942,  2.18246389, -1.62832469]])

In [76]:
a=np.random.randint(1,30,(10,3))
a

array([[ 1, 15,  8],
       [21, 20, 10],
       [16, 11, 15],
       [28, 16, 19],
       [16,  7, 22],
       [29, 26, 22],
       [29, 25, 29],
       [ 4, 23, 19],
       [ 5, 28, 25],
       [16, 22, 16]])

In [77]:
a[1:5]

array([[21, 20, 10],
       [16, 11, 15],
       [28, 16, 19],
       [16,  7, 22]])

In [78]:
a[2:,:2]

array([[16, 11],
       [28, 16],
       [16,  7],
       [29, 26],
       [29, 25],
       [ 4, 23],
       [ 5, 28],
       [16, 22]])

In [79]:
a

array([[ 1, 15,  8],
       [21, 20, 10],
       [16, 11, 15],
       [28, 16, 19],
       [16,  7, 22],
       [29, 26, 22],
       [29, 25, 29],
       [ 4, 23, 19],
       [ 5, 28, 25],
       [16, 22, 16]])

In [80]:
a>10

array([[False,  True, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [81]:
a[a<10]

array([1, 8, 7, 4, 5])

In [ ]:
a[a>10].sum

In [83]:
a.min()

1

In [85]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [89]:
print(a+b)
print("*****************")
print(a+b)
print("__________________________")
print(a*b)
print("$$$$$$$$$$$$$$$$$$$$$$")
print(a/b)


[[10 12 14]
 [16 18 20]
 [22 24 26]]
*****************
[[10 12 14]
 [16 18 20]
 [22 24 26]]
__________________________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$$$$$$$$$$
[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]


In [91]:
# 0 to 15-------->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [92]:
print(np.mean(a))

7.0


In [93]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [94]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
np.log2(2)

1.0

In [96]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [97]:
np.exp(1)

2.718281828459045

In [98]:
np.sin(30)

-0.9880316240928618

In [99]:
np.cos(0)

1.0

In [100]:
np.tan(45)

1.6197751905438615

In [101]:
import numpy
dir (numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

### Pandas 
- pandas is the datascience package
- It is used for
    - data manipulation(modification and updatations)
    - data analysis
    - data cleaning (to remove unnecessary data from data sets) 
- contains mainly two data structure in pandas
    - series-----sequence of data
    - Data frame--Data with row and column